#!/usr/bin/python
# Auto-generated by extend_network.py -- HIP-VPLS full mesh, kernel data plane.
# Provider core: 192.168.3.0/24 ; customer L2 (VPLS): 192.168.1.0/24

import os
import subprocess
import importlib.util

from mininet.topo import Topo
from mininet.net import Mininet
from mininet.node import Node, OVSController, OVSKernelSwitch
from mininet.log import setLogLevel, info
from mininet.cli import CLI


def dataplane_mode( router_dir ):
    """Read dataplane_mode from a router's config.py (default 'threads').

    The data-plane choice lives in router<N>/hiplib/config/config.py, so the
    topology script reads it from there rather than duplicating the setting.
    config.py is a plain dict with no imports, so executing it is cheap/safe.
    """
    cfg_path = os.path.join( os.path.dirname( os.path.abspath( __file__ ) ),
                             router_dir, "hiplib", "config", "config.py" )
    try:
        spec = importlib.util.spec_from_file_location( "hipls_cfg_" + router_dir, cfg_path )
        mod = importlib.util.module_from_spec( spec )
        spec.loader.exec_module( mod )
        return mod.config[ "switch" ].get( "dataplane_mode", "threads" )
    except Exception as e:
        info( "*** Could not read %s dataplane_mode (%s); assuming 'threads'\n" % ( router_dir, e ) )
        return "threads"


class LinuxRouter( Node ):
    "A Node with IP forwarding enabled."
    def config( self, **params ):
        super( LinuxRouter, self).config( **params )
        self.cmd( 'sysctl net.ipv4.ip_forward=1' )
    def terminate( self ):
        self.cmd( 'sysctl net.ipv4.ip_forward=0' )
        super( LinuxRouter, self ).terminate()


class NetworkTopo( Topo ):
    def build( self, **_opts ):
        # Provider core switch: every r<i>-eth1 attaches here.
        core = self.addSwitch( 's1000', cls=OVSKernelSwitch )
        # ---- PE 1 ----
        r1 = self.addNode( 'r1', cls=LinuxRouter )
        s1 = self.addSwitch( 's1', cls=OVSKernelSwitch )
        self.addLink( core, r1, intfName2='r1-eth1', params2={ 'ip' : '192.168.3.1/24' } )
        self.addLink( s1, r1, intfName2='r1-eth0', params2={ 'ip' : '192.168.1.1/24' } )
        h1 = self.addHost( 'h1', ip='192.168.1.100/24', defaultRoute='via 192.168.1.1' )
        self.addLink( h1, s1 )
        # ---- PE 2 ----
        r2 = self.addNode( 'r2', cls=LinuxRouter )
        s2 = self.addSwitch( 's2', cls=OVSKernelSwitch )
        self.addLink( core, r2, intfName2='r2-eth1', params2={ 'ip' : '192.168.3.2/24' } )
        self.addLink( s2, r2, intfName2='r2-eth0', params2={ 'ip' : '192.168.1.2/24' } )
        h2 = self.addHost( 'h2', ip='192.168.1.101/24', defaultRoute='via 192.168.1.2' )
        self.addLink( h2, s2 )
        # ---- PE 3 ----
        r3 = self.addNode( 'r3', cls=LinuxRouter )
        s3 = self.addSwitch( 's3', cls=OVSKernelSwitch )
        self.addLink( core, r3, intfName2='r3-eth1', params2={ 'ip' : '192.168.3.3/24' } )
        self.addLink( s3, r3, intfName2='r3-eth0', params2={ 'ip' : '192.168.1.3/24' } )
        h3 = self.addHost( 'h3', ip='192.168.1.102/24', defaultRoute='via 192.168.1.3' )
        self.addLink( h3, s3 )
        # ---- PE 4 ----
        r4 = self.addNode( 'r4', cls=LinuxRouter )
        s4 = self.addSwitch( 's4', cls=OVSKernelSwitch )
        self.addLink( core, r4, intfName2='r4-eth1', params2={ 'ip' : '192.168.3.4/24' } )
        self.addLink( s4, r4, intfName2='r4-eth0', params2={ 'ip' : '192.168.1.4/24' } )
        h4 = self.addHost( 'h4', ip='192.168.1.103/24', defaultRoute='via 192.168.1.4' )
        self.addLink( h4, s4 )


def run():
    topo = NetworkTopo()
    net = Mininet( topo=topo, switch=OVSKernelSwitch, controller=OVSController )
    net.start()
    info( net[ 'r1' ].cmd( 'ifconfig r1-eth1 192.168.3.1 netmask 255.255.255.0' ) )
    info( net[ 'r2' ].cmd( 'ifconfig r2-eth1 192.168.3.2 netmask 255.255.255.0' ) )
    info( net[ 'r3' ].cmd( 'ifconfig r3-eth1 192.168.3.3 netmask 255.255.255.0' ) )
    info( net[ 'r4' ].cmd( 'ifconfig r4-eth1 192.168.3.4 netmask 255.255.255.0' ) )
    info( net[ 'h1' ].cmd( 'ifconfig h1-eth0 mtu 1400' ) )
    info( net[ 'h2' ].cmd( 'ifconfig h2-eth0 mtu 1400' ) )
    info( net[ 'h3' ].cmd( 'ifconfig h3-eth0 mtu 1400' ) )
    info( net[ 'h4' ].cmd( 'ifconfig h4-eth0 mtu 1400' ) )
    info( net[ 's1' ].cmd( 'ovs-vsctl set bridge s1 stp_enable=true' ) )
    info( net[ 's2' ].cmd( 'ovs-vsctl set bridge s2 stp_enable=true' ) )
    info( net[ 's3' ].cmd( 'ovs-vsctl set bridge s3 stp_enable=true' ) )
    info( net[ 's4' ].cmd( 'ovs-vsctl set bridge s4 stp_enable=true' ) )



    # Per-PE NIC offload tuning, selected by each router's dataplane_mode:
    #
    #   * "threads" / "processes" -> the data plane is a Python raw AF_PACKET
    #     socket loop (the "processes" variant just forks RX decryption into a
    #     second process; the I/O model is the same). The raw socket must see
    #     individual link-MTU Ethernet frames, so segmentation / checksum /
    #     scatter-gather offloads (GSO/TSO/GRO/SG) are turned OFF on that PE's
    #     core + customer NICs and on its attached host. Left on, the stack hands
    #     oversized/coalesced buffers to the socket and throughput collapses
    #     (this is the same incantation that makes iperf work in threads mode).
    #
    #   * "kernel" -> the data plane runs entirely in the kernel (gretap + XFRM
    #     ESP); offloads are left ON so GSO/TSO/GRO can push large segments at
    #     line rate. Nothing to do here.
    routers = { 'r1': 'router1', 'r2': 'router2', 'r3': 'router3', 'r4': 'router4' }
    hosts   = { 'r1': 'h1',      'r2': 'h2',      'r3': 'h3',      'r4': 'h4' }
    for r, rdir in routers.items():
        mode = dataplane_mode( rdir )
        info( "*** %s data-plane mode: %s\n" % ( r, mode ) )
        if mode == "kernel":
            continue  # leave GSO/TSO/GRO on for the kernel data plane
        # Python data plane (threads/processes): disable offloads on the PE's
        # core (eth1) + customer (eth0) NICs and on its attached host.
        info( net[ r ].cmd( '/sbin/ethtool -K %s-eth0 rx off tx off sg off' % r ) )
        info( net[ r ].cmd( '/sbin/ethtool -K %s-eth1 rx off tx off sg off' % r ) )
        h = hosts[ r ]
        info( net[ h ].cmd( '/sbin/ethtool -K %s-eth0 rx off tx off sg off' % h ) )

    # Start HIP-VPLS on each PE.
    #
    # Use node.popen() rather than node.cmd('... &'). popen() runs the daemon
    # directly in the node's namespace via mnexec, detached from the node's
    # persistent interactive shell and its controlling PTY. cmd('... &') instead
    # backgrounds the daemon *inside* that interactive shell: fine for the
    # single-process "threads" / "kernel" modes, but "processes" mode forks an
    # extra RX worker (multiprocessing), and a backgrounded process group under
    # the shell's PTY gets stopped on tty access -- which is why "processes" only
    # ran when started by hand in a fresh terminal. popen() gives every mode that
    # same clean, shell-independent session, so one launch line works for
    # threads, processes and kernel alike.
    #
    # popen() defaults stdout/stderr to pipes that nobody drains; a long-running
    # daemon would block once the ~64K buffer fills, so each PE's output is sent
    # to router<N>/switchd.console.log instead.
    switchd_procs = []
    for r, rdir in routers.items():
        info( '*** Running HIPLS on %s (%s mode)\n' % ( r, dataplane_mode( rdir ) ) )
        logf = open( os.path.join( rdir, 'switchd.console.log' ), 'ab' )
        proc = net[ r ].popen( 'cd %s && exec python3 switchd.py' % rdir,
                               shell=True, stdout=logf, stderr=subprocess.STDOUT )
        switchd_procs.append( ( proc, logf ) )

    CLI( net )

    # Stop the daemons before tearing down the namespaces.
    for proc, logf in switchd_procs:
        try:
            proc.terminate()
        except Exception:
            pass
        try:
            logf.close()
        except Exception:
            pass

    net.stop()


if __name__ == '__main__':
    setLogLevel( 'info' )
    run()
